// pyo3 0.22's `#[pyfunction]` macro expansion emits an `.into()` on the
// returned `PyResult`, which clippy flags as useless. The conversion is
// real code generated by the macro — not something we can remove — so
// the allow is scoped to this file rather than crate-wide.
#![allow(clippy::useless_conversion)]

use pyo3::prelude::*;

pub mod catalog;
pub mod detect;
pub mod error;
pub mod graph;
pub mod ingestion;
pub(crate) mod json_py;
pub(crate) mod parse;
pub mod plan_parser;
pub(crate) mod py_exceptions;
pub mod resolved;
pub mod rules;
mod semantic;
pub mod session;
pub mod types;

pub use py_exceptions::{BurntEngineError, CatalogError, IoError, ParseError, RuleError};

use detect::detect_mode_from_source;
use error::EngineError;
use graph::{Graph, PipelineGraph, PyGraph, PyPipeline};
use ingestion::files::ingest_file;
use plan_parser::{parse_physical_plan_py, PyPlanNode};
use resolved::python::{
    resolve_graph, PyNodeOverlay, PyPlanSubtree, PyPlanSubtreeNode, PyResolvedGraph,
    PyStageObservation, PyTableSpec,
};
use session::{session_collect, session_start, SessionStatePy};
use types::{
    AnalysisMode, AnalysisResultPy, Cell, CellKind, Finding, PyAstShape, PyEdge, PyNode,
    PyPipelineTable, PyScopeFacts, PyTableRef, RuleEntry,
};

/// Returns the crate version string from `Cargo.toml`.
#[pyfunction]
fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// Builds a cost/pipeline graph for `source` using auto-detected language mode.
///
/// Returns a `PyGraph` for Python/SQL input and a `PyPipeline` for DLT.
#[pyfunction]
fn check(source: &str) -> PyResult<PyObject> {
    let mode = detect_mode_from_source(source);

    Python::with_gil(|py| match mode {
        AnalysisMode::Sdp => {
            let pg = PipelineGraph::from_sdp(source);
            let pg_py: PyPipeline = pg.into();
            Ok(pg_py.into_py(py))
        }
        AnalysisMode::Sql => {
            let cg = Graph::from_sql(source)?;
            let cg_py: PyGraph = cg.into();
            Ok(cg_py.into_py(py))
        }
        AnalysisMode::Python => {
            let cg = Graph::from_python(source)?;
            let cg_py: PyGraph = cg.into();
            Ok(cg_py.into_py(py))
        }
    })
}

/// Runs all applicable lint rules against `source`.
///
/// `language` may be `"python"`, `"sql"`, `"sdp"`, or `"auto"` / `None` for
/// auto-detection.  Returns a list of `Finding` objects.
#[pyfunction]
#[pyo3(signature = (source, language=None))]
fn run_rules(source: &str, language: Option<&str>) -> PyResult<Vec<types::Finding>> {
    let lang = match language {
        Some("auto") | None => detect_mode_from_source(source).as_lang_str(),
        Some(l) => l,
    };
    Ok(rules::run(source, lang)?)
}

/// Runs all applicable lint rules against `source`, enriching table specs from
/// the Databricks Unity Catalog REST API when `catalog_url` is provided.
///
/// When `catalog_url` is `None` the call is identical to `run_rules`. When
/// provided, it enables rules marked `requires_catalog = true` — these rules
/// fire only when table schemas or properties are available from the catalog.
#[pyfunction]
#[pyo3(signature = (source, language=None, catalog_url=None, catalog_token=None))]
fn run_rules_with_catalog(
    py: Python<'_>,
    source: &str,
    language: Option<&str>,
    catalog_url: Option<&str>,
    catalog_token: Option<&str>,
) -> PyResult<Vec<types::Finding>> {
    let lang = match language {
        Some("auto") | None => detect_mode_from_source(source).as_lang_str(),
        Some(l) => l,
    };
    py.allow_threads(|| {
        if let Some(url) = catalog_url {
            let all_rules = rules::load_all_compiled();
            let client = catalog::databricks::DatabricksCatalogClient::new(url, catalog_token);
            Ok(rules::graph_pipeline::run_graph_rules_with_catalog(
                source, lang, &all_rules, &client,
            ))
        } else {
            Ok(rules::run(source, lang)?)
        }
    })
}

/// Returns metadata for every rule in the registry.
#[pyfunction]
fn list_rules() -> Vec<RuleEntry> {
    rules::list_all()
}

/// Returns the total number of rules currently registered.
#[pyfunction]
pub fn get_registry_count() -> usize {
    rules::get_registry_count()
}

/// Builds a graph/pipeline for the given mode and returns it alongside any
/// semantic findings produced during graph construction.
#[allow(clippy::type_complexity)]
fn build_graph_and_pipeline(
    mode: &AnalysisMode,
    source: &str,
) -> Result<(Option<PyGraph>, Option<PyPipeline>, Vec<Finding>), EngineError> {
    match mode {
        AnalysisMode::Sdp => {
            let pg = PipelineGraph::from_sdp(source);
            Ok((None, Some(pg.into()), Vec::new()))
        }
        AnalysisMode::Sql => {
            let cg = Graph::from_sql(source).map_err(|e| EngineError::GraphBuild(e.to_string()))?;
            Ok((Some(cg.into()), None, Vec::new()))
        }
        AnalysisMode::Python => {
            let cg =
                Graph::from_python(source).map_err(|e| EngineError::GraphBuild(e.to_string()))?;
            let sem_findings = cg.findings.clone();
            Ok((Some(cg.into()), None, sem_findings))
        }
    }
}

/// Analyses an in-memory source string and returns a full `AnalysisResultPy`.
///
/// `path` is optional and used only to populate `result.path`.
#[pyfunction]
#[pyo3(signature = (source, path=None))]
fn analyze_source(py: Python<'_>, source: &str, path: Option<&str>) -> PyResult<AnalysisResultPy> {
    py.allow_threads(|| {
        let mode = detect_mode_from_source(source);
        let mut findings = rules::run(source, mode.as_lang_str())?;

        let cell = Cell {
            kind: match mode {
                AnalysisMode::Sdp => CellKind::Python,
                AnalysisMode::Sql => CellKind::Sql,
                AnalysisMode::Python => CellKind::Python,
            },
            source: source.to_string(),
            byte_offset: 0,
            line_offset: 0,
            origin_path: path.map(std::path::PathBuf::from),
        };

        let (graph, pipeline, sem_findings) = build_graph_and_pipeline(&mode, source)?;
        findings.extend(sem_findings);

        Ok(AnalysisResultPy {
            mode: mode.to_string(),
            graph,
            pipeline,
            findings,
            cells: vec![cell],
            path: path.map(String::from),
        })
    })
}

fn analyze_path_internal(path: &str) -> Result<AnalysisResultPy, EngineError> {
    let source_file = ingest_file(path)?;
    let mode = detect_mode_from_source(&source_file.content);
    let mut findings = rules::run(&source_file.content, mode.as_lang_str()).unwrap_or_default();
    let (graph, pipeline, sem_findings) = build_graph_and_pipeline(&mode, &source_file.content)?;
    findings.extend(sem_findings);
    Ok(AnalysisResultPy {
        mode: mode.to_string(),
        graph,
        pipeline,
        findings,
        cells: source_file.cells,
        path: Some(path.to_string()),
    })
}

/// Analyses a file on disk and returns a full `AnalysisResultPy`.
#[pyfunction]
fn analyze_file(py: Python<'_>, path: &str) -> PyResult<AnalysisResultPy> {
    py.allow_threads(|| Ok(analyze_path_internal(path)?))
}

/// Analyses all `.py`, `.sql`, and `.ipynb` files in a directory in parallel.
///
/// Returns one `AnalysisResultPy` per file.  Files that fail to parse are
/// silently skipped.
#[pyfunction]
fn analyze_directory(py: Python<'_>, path: &str) -> PyResult<Vec<AnalysisResultPy>> {
    py.allow_threads(|| {
        use rayon::prelude::*;

        let dir = std::path::Path::new(path);
        if !dir.exists() {
            return Err(EngineError::FileNotFound(path.to_string()).into());
        }
        if !dir.is_dir() {
            return Err(EngineError::Internal(format!("not a directory: {path}")).into());
        }

        let entries: Vec<_> = std::fs::read_dir(dir)
            .map_err(|e| -> EngineError { EngineError::Io(e) })?
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_file())
            .map(|e| e.path())
            .filter(|p| {
                let ext = p.extension().and_then(|e| e.to_str()).unwrap_or("");
                ext == "py" || ext == "sql" || ext == "ipynb"
            })
            .collect();

        let results: Vec<AnalysisResultPy> = entries
            .par_iter()
            .filter_map(|path| analyze_path_internal(&path.to_string_lossy()).ok())
            .collect();

        Ok(results)
    })
}

#[pymodule]
fn _engine(m: &Bound<'_, PyModule>) -> PyResult<()> {
    // Exception hierarchy — registered first so Python's `from _engine import
    // ParseError` works immediately.
    m.add(
        "BurntEngineError",
        m.py().get_type_bound::<BurntEngineError>(),
    )?;
    m.add("ParseError", m.py().get_type_bound::<ParseError>())?;
    m.add("RuleError", m.py().get_type_bound::<RuleError>())?;
    m.add("CatalogError", m.py().get_type_bound::<CatalogError>())?;
    m.add("IoError", m.py().get_type_bound::<IoError>())?;

    m.add_function(wrap_pyfunction!(version, m)?)?;
    m.add_function(wrap_pyfunction!(check, m)?)?;
    m.add_function(wrap_pyfunction!(run_rules, m)?)?;
    m.add_function(wrap_pyfunction!(run_rules_with_catalog, m)?)?;
    m.add_function(wrap_pyfunction!(list_rules, m)?)?;
    m.add_function(wrap_pyfunction!(get_registry_count, m)?)?;
    m.add_function(wrap_pyfunction!(analyze_source, m)?)?;
    m.add_function(wrap_pyfunction!(analyze_file, m)?)?;
    m.add_function(wrap_pyfunction!(analyze_directory, m)?)?;
    m.add_function(wrap_pyfunction!(session_start, m)?)?;
    m.add_function(wrap_pyfunction!(session_collect, m)?)?;
    m.add_function(wrap_pyfunction!(parse_physical_plan_py, m)?)?;
    m.add_function(wrap_pyfunction!(resolve_graph, m)?)?;

    m.add_class::<SessionStatePy>()?;
    m.add_class::<PyPlanNode>()?;
    m.add_class::<PyGraph>()?;
    m.add_class::<PyPipeline>()?;
    m.add_class::<PyNode>()?;
    m.add_class::<PyEdge>()?;
    m.add_class::<PyTableRef>()?;
    m.add_class::<PyAstShape>()?;
    m.add_class::<PyScopeFacts>()?;
    m.add_class::<PyPipelineTable>()?;
    m.add_class::<PyResolvedGraph>()?;
    m.add_class::<PyNodeOverlay>()?;
    m.add_class::<PyStageObservation>()?;
    m.add_class::<PyPlanSubtree>()?;
    m.add_class::<PyPlanSubtreeNode>()?;
    m.add_class::<PyTableSpec>()?;
    m.add_class::<types::Finding>()?;
    m.add_class::<rules::PyRuleInfo>()?;
    m.add_class::<Cell>()?;
    m.add_class::<CellKind>()?;
    m.add_class::<AnalysisMode>()?;
    m.add_class::<types::Severity>()?;
    m.add_class::<types::Confidence>()?;
    m.add_class::<RuleEntry>()?;
    m.add_class::<AnalysisResultPy>()?;

    Ok(())
}
