# BP003 - Databricks magic (# MAGIC) in plain Python file
# Category: BestPractice
# Severity: warning
# Language: python

[rule]
id = "magic_in_plain"
code = "BP003"
severity = "warning"
language = "python"
description = "Databricks magic (# MAGIC) in plain Python file"
suggestion = "Remove magic or use .py (Databricks) extension"
category = "BestPractice"

[query]
cpl_detect = """
# MAGIC $cmd
"""
